local v1,v2,v3=game:GetService("\80\108\97\121\101\114\115"),game:GetService("\87\111\114\107\115\112\97\99\101"),game:GetService("\82\117\110\83\101\114\118\105\99\101");local v4=v1.LocalPlayer;if not v4 then repeat wait(1)v4=v1.LocalPlayer until v4 end;local v5,v6,v7,v8=Vector2.new,Vector3.new,Color3.fromRGB,Drawing.new;local v9=v4:GetMouse();local v10,v11,v12=getgenv,setrobloxinput,string.format
local function x1(a,b,c)if a>c then return c elseif a<b then return b else return a end end;local function x2()return v5(v9.X,v9.Y)end;local function x3(a,b,c)return a+(b-a)*c end;local function x4(t)for _,d in pairs(t)do d.Visible=false end end;local function x5(t)for _,d in pairs(t)do d:Remove()end end
local L={};L.__index=L;function L.n(n,s,w)local o=setmetatable({},L)o.i={['m1']={id=0x01,h=false,c=false},['end']={id=0x23,h=false,c=false}}o.a=nil;o.o=true;o.l=nil;o.w=true;o.b=0;o.t=os.clock()o.d=n;o.k=w;o.X,o.Y=20,60;o.W=s and s.x or 300;o.H=s and s.y or 400;o.z=nil
o.c1=v7(255,127,0)o.c2=v7(255,255,255)o.c3=v7(0,0,0)o.c4=v7(25,25,25)o.c5=v7(38,38,38)o.c6=v7(76,76,76)o.th,o.tb,o.p=25,20,6;local function nd(t,p)local d=v8(t)for k,v in pairs(p)do d[k]=v end;return d end
local b,r,d,nb,tl=nd('Square',{Filled=true,Color=o.c5}),nd('Square',{Filled=false,Thickness=1,Color=o.c3}),nd('Square',{Filled=false,Thickness=1,Color=o.c4}),nd('Square',{Filled=true,Color=o.c4}),nd('Text',{Text=o.d,Outline=true,Color=o.c2})
local wb,wc,wr,wd,wt=nd('Square',{Filled=true,Color=o.c5}),nd('Square',{Filled=true,Color=o.c1}),nd('Square',{Filled=false,Thickness=1,Color=o.c3}),nd('Square',{Filled=false,Thickness=1,Color=o.c4}),nd('Text',{Text=n,Outline=true,Color=o.c2})
o.tr={['_tabs']={},['_drawings']={r,d,b,nb,tl,wb,wc,wr,wd,wt}}return o end;function L._g(s)return #s*7,13 end;function L._m(o,s)local m=x2()return m.x>=o.x and m.x<=o.x+s.x and m.y>=o.y and m.y<=o.y+s.y end;function L:TM(s)self.o=s end
function L:_r()if self.z then x5(self.z['_drawings'])self.z=nil end end;function L:_s(d,c,cb,p,w)if self.z then self:_r()end;local dr={}local b=v8('Square');b.Filled=true;b.Color=self.c5;table.insert(dr,b)local bd=v8('Square');bd.Filled=false;bd.Thickness=1;bd.Color=self.c4;table.insert(dr,bd)
for _,ch in ipairs(c)do local t=v8('Text');t.Outline=true;t.Color=self.c2;t.Text=ch;table.insert(dr,t)end;self.z={['choices']=c,['callback']=cb,['pos']=p,['w']=w,['_drawings']=dr}end
function L:T(n)local b,s,c,t=v8('Square'),v8('Square'),v8('Square'),v8('Text');b.Color=self.c4;b.Filled=true;s.Color=self.c3;s.Filled=true;c.Color=self.c1;c.Filled=true;t.Color=self.c2;t.Outline=true;t.Text=n;table.insert(self.tr['_tabs'],{['name']=n,['_sections']={},['_drawings']={b,s,c,t}})if self.a==nil then self.a=n end;return n end
function L:S(tn,n)for _,t in ipairs(self.tr['_tabs'])do if t['name']==tn then local b,c,bd,ti=v8('Square'),v8('Square'),v8('Square'),v8('Text');b.Filled=true;b.Color=self.c5;c.Filled=false;c.Thickness=1;c.Color=self.c3;bd.Filled=false;bd.Thickness=1;bd.Color=self.c6;ti.Text=n;ti.Outline=true;ti.Color=self.c2;local s={['name']=n,['_items']={},['_drawings']={b,c,bd,ti}}table.insert(t._sections,s)return n end end end
function L:_a(tn,sn,i)for _,t in pairs(self.tr._tabs)do if t.name==tn then for _,s in pairs(t._sections)do if s.name==sn then table.insert(s._items,i)return end end end end end
function L:C(tn,sn,l,d,c)local o,ch,cs,t=v8('Square'),v8('Square'),v8('Square'),v8('Text');o.Color=self.c3;o.Thickness=1;o.Filled=false;ch.Color=self.c1;ch.Filled=true;cs.Color=self.c3;cs.Filled=true;t.Color=self.c2;t.Outline=true;t.Text=l;self:_a(tn,sn,{['type']='checkbox',['value']=d,['callback']=c,['_drawings']={o,ch,cs,t}})end
function L:Sl(tn,sn,l,d,c,mn,mx,st,ap)local o,f,fs,v,t=v8('Square'),v8('Square'),v8('Square'),v8('Text'),v8('Text');o.Color=self.c3;o.Filled=true;f.Color=self.c1;f.Filled=true;fs.Color=self.c3;fs.Filled=true;v.Color=self.c2;v.Outline=true;v.Text=l;t.Color=self.c2;t.Outline=true;t.Text=l;self:_a(tn,sn,{['type']='slider',['value']=d,['callback']=c,['min']=mn,['max']=mx,['step']=st,['appendix']=ap,['_drawings']={o,f,fs,v,t}})end
function L:Ch(tn,sn,l,d,c,ch)local o,f,vt,lt=v8('Square'),v8('Square'),v8('Text'),v8('Text');o.Color=self.c3;o.Thickness=1;o.Filled=false;f.Color=self.c3;f.Filled=true;local it=d;if type(d)=="table"then if #d==0 then it="None"else it=table.concat(d,", ")end end;vt.Color=self.c2;vt.Outline=true;vt.Text=tostring(it)lt.Color=self.c2;lt.Outline=true;lt.Text=l;local i={['type']='choice',['value']=d,['callback']=c,['choices']=ch,['_drawings']={o,f,vt,lt}}self:_a(tn,sn,i)return i end
function L:DC(tn,sn,l1,d1,c1,ch1,l2,d2,c2,ch2)local o1,f1,v1,lb1,o2,f2,v2,lb2=v8('Square'),v8('Square'),v8('Text'),v8('Text'),v8('Square'),v8('Square'),v8('Text'),v8('Text');o1.Color=self.c3;o1.Thickness=1;o1.Filled=false;f1.Color=self.c3;f1.Filled=true;v1.Color=self.c2;v1.Outline=true;v1.Text=tostring(d1);lb1.Color=self.c2;lb1.Outline=true;lb1.Text=l1;o2.Color=self.c3;o2.Thickness=1;o2.Filled=false;f2.Color=self.c3;f2.Filled=true;v2.Color=self.c2;v2.Outline=true;v2.Text=tostring(d2);lb2.Color=self.c2;lb2.Outline=true;lb2.Text=l2;local i={['type']='dual_choice',['v1']=d1,['cb1']=c1,['ch1']=ch1,['v2']=d2,['cb2']=c2,['ch2']=ch2,['_drawings']={o1,f1,v1,lb1,o2,f2,v2,lb2}}self:_a(tn,sn,i)return i end
function L:St()local dt=math.max(os.clock()-self.t,0.0035)local mp=x2()local m1=iskeypressed(0x01)if m1 and not self.i.m1.h then self.i.m1.c=true else self.i.m1.c=false end;self.i.m1.h=m1;local mo=self.o;local cf=mo and self.i.m1.c;local bo=self.b;local cv=bo>0.22;self.b=x1(x3(bo,mo and 1 or 0,dt*11),0,1);if self.l~=mo then v11(not mo)self.l=mo end;local wb,wc,wr,wd,wt=unpack(self.tr['_drawings'],6,10)if self.w then local st=self.d;if self.k then for _,a in ipairs(self.k)do local s=a()if s then st=st.." | "..s end end end;local ww=#st*7;local wp=v5(20,20)local ws=v5(ww+18,30)wb.Position=wp;wb.Size=ws;wb.Visible=true;wr.Position=wp;wr.Size=ws;wr.Visible=true;wd.Position=wp+v5(1,1)wd.Size=ws+v5(-2,-2)wd.Visible=true;wc.Position=wp+v5(2,2)wc.Size=v5(ws.x-4,1)wc.Visible=true;wt.Position=wp+v5(8,8)wt.Text=st;wt.Visible=true else wb.Visible=false;wt.Visible=false end
local cr,bd,b,nb,ti=unpack(self.tr['_drawings'],1,5)b.Position=v5(self.X,self.Y);b.Size=v5(self.W,self.H);b.Transparency=bo;b.Visible=cv;bd.Position=v5(self.X+1,self.Y+1)bd.Size=v5(self.W-2,self.H-2)bd.Transparency=bo;bd.Visible=cv;cr.Position=v5(self.X,self.Y)cr.Size=v5(self.W,self.H)cr.Transparency=bo;cr.Visible=cv;nb.Position=v5(self.X+2,self.Y+2)nb.Size=v5(self.W-4,self.th-4)nb.Transparency=bo;nb.Visible=cv;ti.Position=v5(self.X+7,self.Y+4)ti.Transparency=bo;ti.Visible=cv
local tr=v5(self.W,self.th)if self._m(v5(self.X,self.Y),tr)and cf then self.dg=true;self.do_=mp-v5(self.X,self.Y)end;if self.dg then if self.i.m1.h then self.X=mp.x-self.do_.x;self.Y=mp.y-self.do_.y else self.dg=false end end
local nt=#self.tr['_tabs']for ti,t in ipairs(self.tr['_tabs'])do local to=self.a==t['name']local tw=(self.W-12-(nt-1)*2)/nt;local tp=v5(self.X+6+(ti-1)*(tw+2),self.Y+self.th+6)t['_drawings'][1].Position=tp;t['_drawings'][1].Size=v5(tw,self.tb)t['_drawings'][1].Transparency=bo;t['_drawings'][1].Visible=cv;t['_drawings'][3].Position=tp;t['_drawings'][3].Size=v5(tw,1)t['_drawings'][3].Transparency=bo;t['_drawings'][3].Visible=to and cv;t['_drawings'][4].Position=tp+v5(4,4)t['_drawings'][4].Transparency=bo;t['_drawings'][4].Visible=cv
if cf and self._m(tp,v5(tw,self.tb))then self.a=t['name']end;if to then local sy=self.p*2+self.tb+self.th;for _,s in ipairs(t['_sections'])do local sp=v5(self.X+10,self.Y+sy)local sw=self.W-20;local iy=20;for _,i in ipairs(s._items)do local ip=sp+v5(10,iy)
if i.type=='checkbox'then local bs=v5(15,15)i._drawings[1].Position=ip;i._drawings[1].Size=bs;i._drawings[1].Visible=cv;i._drawings[2].Position=ip+v5(1,1)i._drawings[2].Size=bs-v5(2,2)i._drawings[2].Visible=i.value and cv;i._drawings[3].Position=ip+v5(1,bs.y-2)i._drawings[3].Size=v5(bs.x-2,1)i._drawings[3].Visible=i.value and cv;i._drawings[4].Position=ip+v5(22,0)i._drawings[4].Visible=cv;if self._m(ip,v5(sw-20,16))and cf then i.value=not i.value;if i.callback then i.callback(i.value)end end;iy=iy+25
elseif i.type=='slider'then local slw=sw-30;i._drawings[5].Position=ip;i._drawings[5].Visible=cv;i._drawings[1].Position=ip+v5(0,15)i._drawings[1].Size=v5(slw,10)i._drawings[1].Visible=cv;local pc=(i.value-i.min)/(i.max-i.min)i._drawings[2].Position=ip+v5(1,16)i._drawings[2].Size=v5((slw-2)*pc,8)i._drawings[2].Visible=cv;i._drawings[4].Position=ip+v5(slw-40,0)i._drawings[4].Text=tostring(i.value)..(i.appendix or"")i._drawings[4].Visible=cv;if self.i.m1.h and self._m(ip+v5(0,15),v5(slw,10))then local mx=mp.x-(ip.x)local np=x1(mx/slw,0,1)local nv=math.floor((i.min+(i.max-i.min)*np)/i.step+0.5)*i.step;if nv~=i.value then i.value=nv;if i.callback then i.callback(nv)end end end;iy=iy+35
elseif i.type=='choice'then local cw=sw-30;local ch=20;i._drawings[4].Position=ip;i._drawings[4].Visible=cv;i._drawings[1].Position=ip+v5(0,15)i._drawings[1].Size=v5(cw,ch)i._drawings[1].Visible=cv;i._drawings[2].Position=ip+v5(2,17)i._drawings[2].Size=v5(cw-4,ch-4)i._drawings[2].Visible=cv;local dt=i.value;if type(i.value)=="table"then if #i.value>0 then dt=table.concat(i.value,", ")if #dt>20 then dt=#i.value.." sel"end else dt="None"end end;i._drawings[3].Position=ip+v5(4,18)i._drawings[3].Text=tostring(dt)i._drawings[3].Visible=cv;if cf and self._m(ip+v5(0,15),v5(cw,ch))then local cb=function(v)if type(i.value)=="table"then local f=false;for idx,val in ipairs(i.value)do if val==v then table.remove(i.value,idx)f=true;break end end;if not f then table.insert(i.value,v)end;if i.callback then i.callback(i.value)end else i.value=v;if i.callback then i.callback(v)end end end;cf=false;self:_s(i.value,i.choices,cb,ip+v5(0,35),cw)end;iy=iy+40
elseif i.type=='dual_choice'then local fw=sw-30;local hw=(fw/2)-5;local ch=20;local p1=ip+v5(0,15)local p2=ip+v5(hw+10,15)i._drawings[4].Position=ip;i._drawings[4].Visible=cv;i._drawings[1].Position=p1;i._drawings[1].Size=v5(hw,ch)i._drawings[1].Visible=cv;i._drawings[2].Position=p1+v5(1,1)i._drawings[2].Size=v5(hw-2,ch-2)i._drawings[2].Visible=cv;local d1=i.v1;if type(d1)=="table"then if #d1>0 then d1=table.concat(d1,", ")if #d1>10 then d1=#i.v1.." sel"end else d1="None"end end;i._drawings[3].Position=p1+v5(4,3)i._drawings[3].Text=tostring(d1)i._drawings[3].Visible=cv;i._drawings[8].Position=ip+v5(hw+10,0)i._drawings[8].Visible=cv;i._drawings[5].Position=p2;i._drawings[5].Size=v5(hw,ch)i._drawings[5].Visible=cv;i._drawings[6].Position=p2+v5(1,1)i._drawings[6].Size=v5(hw-2,ch-2)i._drawings[6].Visible=cv;local d2=i.v2;if type(d2)=="table"then if #d2>0 then d2=table.concat(d2,", ")if #d2>10 then d2=#i.v2.." sel"end else d2="None"end end;i._drawings[7].Position=p2+v5(4,3)i._drawings[7].Text=tostring(d2)i._drawings[7].Visible=cv
if cf and self._m(p1,v5(hw,ch))then local cb=function(v)if type(i.v1)=="table"then local f=false;for idx,val in ipairs(i.v1)do if val==v then table.remove(i.v1,idx)f=true;break end end;if not f then table.insert(i.v1,v)end;if i.cb1 then i.cb1(i.v1)end else i.v1=v;if i.cb1 then i.cb1(v)end end end;cf=false;self:_s(i.v1,i.ch1,cb,p1+v5(0,ch),hw)end;if cf and self._m(p2,v5(hw,ch))then local cb=function(v)if type(i.v2)=="table"then local f=false;for idx,val in ipairs(i.v2)do if val==v then table.remove(i.v2,idx)f=true;break end end;if not f then table.insert(i.v2,v)end;if i.cb2 then i.cb2(i.v2)end else i.v2=v;if i.cb2 then i.cb2(v)end end end;cf=false;self:_s(i.v2,i.ch2,cb,p2+v5(0,ch),hw)end;iy=iy+40 end end
s._drawings[4].Position=sp+v5(10,-8)s._drawings[4].Visible=cv;s._drawings[3].Position=sp;s._drawings[3].Size=v5(sw,iy)s._drawings[3].Visible=cv;sy=sy+iy+10 end else for _,s in pairs(t._sections)do x4(s._drawings)for _,i in pairs(s._items)do x4(i._drawings)end end end end
if self.z then local dd=self.z;local dy=0;dd._drawings[1].Position=dd.pos;dd._drawings[1].Visible=cv;dd._drawings[2].Position=dd.pos;dd._drawings[2].Visible=cv;for i,c in ipairs(dd.choices)do local t=dd._drawings[i+2]t.Position=dd.pos+v5(4,dy+2)t.Visible=cv;if cf and self._m(dd.pos+v5(0,dy),v5(dd.w,16))then dd.callback(c)cf=false end;dy=dy+16 end;dd._drawings[1].Size=v5(dd.w,dy+4)dd._drawings[2].Size=v5(dd.w,dy+4)if cf and not self._m(dd.pos,v5(dd.w,dy))then self:_r()else cf=false end end;self.t=os.clock()end
local rb=v2:WaitForChild("\82\111\99\107\115");local lf=v2:WaitForChild("\76\105\118\105\110\103");local c={A=false,MF=false,CD=0.1,MS=0.1,SC=3,SR=20,MAD=20,MFR=1000,AS=5.0,PMD=10,CRF=rb:WaitForChild("\73\115\108\97\110\100\50\86\111\108\99\97\110\105\99\68\101\112\116\104\115"),TR={},TM={}};local st="Idle"
local function gD(a,b)if not a or not b then return 9e9 end;local x,y,z=a.X-b.X,a.Y-b.Y,a.Z-b.Z;return math.sqrt(x*x+y*y+z*z)end
local function gRT()local t,s={},{}if c.CRF then for _,ci in ipairs(c.CRF:GetChildren())do if(ci:IsA("Part")or ci:IsA("MeshPart"))and ci:GetAttribute("IsOccupied")~=nil then local m=ci:FindFirstChildOfClass("Model")if m and not s[m.Name]then table.insert(t,m.Name)s[m.Name]=true end end end end;table.sort(t)return t end
local function gMT()local t,s={},{}if lf then for _,ci in ipairs(lf:GetChildren())do if ci:IsA("Model")and ci:GetAttribute("IsNpc")==true then local n=string.gsub(ci.Name,"%d+$","")n=string.match(n,"^%s*(.-)%s*$")or n;if not s[n]then table.insert(t,n)s[n]=true end end end end;table.sort(t)return t end
local function gHP(m)if not m then return nil end;local f=m:FindFirstChild("infoFrame")if f then local fr=f:FindFirstChild("Frame")if fr then local l=fr:FindFirstChild("rockHP")if l then return tonumber(string.match(l.Text,"%d+"))end end end;return nil end
local function iS(tp)local e=lf:GetChildren()for _,en in ipairs(e)do if en:IsA("Model")and en.Name~=v4.Name then local r=en:FindFirstChild("HumanoidRootPart")if r then local d=gD(tp,r.Position)if en:GetAttribute("IsNpc")==true then if d<c.SR then return false end else if d<c.PMD then return false end end end end end;return true end
local function gAV(cp)local tx,ty=0,0;local e=lf:GetChildren()for _,en in ipairs(e)do if en:IsA("Model")and en:GetAttribute("IsNpc")==true then local r=en:FindFirstChild("HumanoidRootPart")if r then local d=gD(cp,r.Position)if d<c.MAD and d>0.1 then local px,pz=cp.X-r.Position.X,cp.Z-r.Position.Z;local pd=math.sqrt(px*px+pz*pz)local w=(c.MAD-d)/c.MAD;tx=tx+((px/pd)*w)ty=ty+((pz/pd)*w)end end end end;return tx,ty end
local function mT(tc,sdo,ia)local ch=v4.Character;if not ch then return end;local h=ch:FindFirstChild("HumanoidRootPart")if not h then return end;local cp=h.Position;local cam=v2.CurrentCamera;if cam then pcall(function()if Camera and Camera.lookAt then Camera.lookAt(cam.Position,tc)elseif cam.lookAt then cam:lookAt(cam.Position,tc)end end)end
local dx,dz=cp.X-tc.X,cp.Z-tc.Z;local dc=math.sqrt(dx*dx+dz*dz)local SD=sdo or 5;if dc>0.1 then local dirX,dirZ=dx/dc,dz/dc;local dX=tc.X+(dirX*SD)local dZ=tc.Z+(dirZ*SD)if SD<=0.5 then dX=tc.X;dZ=tc.Z end;local tp=v6(dX,tc.Y,dZ)local dd=gD(tp,cp)local ax,az=0,0;local iAv=false;if not ia then ax,az=gAV(cp)iAv=(math.abs(ax)>0.01 or math.abs(az)>0.01)end
if dd>1 or iAv then local mx,mz=dX-cp.X,dZ-cp.Z;local md=math.sqrt(mx*mx+mz*mz)local mdx,mdz=0,0;if md>0.01 then mdx=mx/md;mdz=mz/md end;local fdx=mdx+(ax*c.AS)local fdz=mdz+(az*c.AS)local fd=math.sqrt(fdx*fdx+fdz*fdz)if fd>0 then fdx=fdx/fd;fdz=fdz/fd end;local ms=dd*c.MS;if ms>c.SC then ms=c.SC end;if not iAv and ms>dd then ms=dd end;local nx=cp.X+(fdx*ms)local nz=cp.Z+(fdz*ms)local ny=cp.Y+(tc.Y-cp.Y)*c.MS;h.Position=v6(nx,ny,nz)h.AssemblyLinearVelocity=v6(fdx*50,0,fdz*50)else h.AssemblyLinearVelocity=v6(0,0,0)end else h.AssemblyLinearVelocity=v6(0,0,0)end end
local function fT()if not c.CRF then return nil,nil end;local ch=c.CRF:GetChildren()local ct,chb,md=nil,nil,9e9;local ch=v4.Character;if not ch then return nil,nil end;local h=ch:FindFirstChild("HumanoidRootPart")if not h then return nil,nil end;local mp=h.Position;for _,sl in ipairs(ch)do if sl:GetAttribute("IsOccupied")==true then local vm=sl:FindFirstChildOfClass("Model")if vm then local rn=vm.Name;local al=false;if #c.TR==0 then al=true else for _,t in ipairs(c.TR)do if t==rn then al=true;break end end end;if al then local hb=vm:FindFirstChild("Hitbox")if hb and iS(hb.Position)then local d=gD(mp,hb.Position)if d<md then md=d;ct=sl;chb=hb end end end end end end;return ct,chb end
local function fMT()local ch=lf:GetChildren()local cm,cr,md=nil,nil,c.MFR;local char=v4.Character;if not char then return nil,nil end;local h=char:FindFirstChild("HumanoidRootPart")if not h then return nil,nil end;local mp=h.Position;local cc=0;for _,e in ipairs(ch)do cc=cc+1;if cc%100==0 then task.wait()end;if e:GetAttribute("IsNpc")==true then local ma=false;local cn=string.gsub(e.Name,"%d+$","")cn=string.match(cn,"^%s*(.-)%s*$")or cn;if #c.TM==0 then ma=true else for _,t in ipairs(c.TM)do if t==cn then ma=true;break end end end;if ma then local hm=e:FindFirstChild("Humanoid")local r=e:FindFirstChild("HumanoidRootPart")if hm and r and hm.Health>0 then local d=gD(mp,r.Position)if d<md then md=d;cm=e;cr=r end end end end end;return cm,cr end
spawn(function()while true do if c.A then local t,h=fT()if t and h then local vm=h.Parent;st="\77\105\110\105\110\103 "..vm.Name;local ad=5;local hl=gHP(vm)or 9e9;local tld=os.clock()while c.A and t.Parent and t:GetAttribute("IsOccupied")==true do local ch=v4.Character;local hrp=ch and ch:FindFirstChild("HumanoidRootPart")if mG.o then st="\80\97\117\115\101\100"if hrp then hrp.AssemblyLinearVelocity=v6(0,0,0)end;break end;local chp=gHP(vm)if chp then if chp<hl then hl=chp;tld=os.clock()elseif(os.clock()-tld)>2 then ad=ad-1;if ad<3 then ad=6 end;tld=os.clock()end end;if h and h.Parent then if not iS(h.Position)then st="\85\110\115\97\102\101";break end;mT(h.Position,ad,false)else break end;pcall(function()mouse1click()keypress(0x31)keyrelease(0x31)end)wait(c.CD)end;wait(0.1)else st="\83\101\97\114\99\104\105\110\103"local ch=v4.Character;if ch then local hrp=ch:FindFirstChild("HumanoidRootPart")if hrp then local cp=hrp.Position;local ax,az=gAV(cp)local am=math.sqrt(ax*ax+az*az)if am>0 then local mdx,mdz=ax/am,az/am;local ms=c.SC;local nx,nz=cp.X+(mdx*ms),cp.Z+(mdz*ms)hrp.Position=v6(nx,cp.Y,nz)hrp.AssemblyLinearVelocity=v6(mdx*50,0,mdz*50)else hrp.AssemblyLinearVelocity=v6(0,0,0)end end end;wait(0.1)end elseif c.MF then local m,mr=fMT()if m and mr then st="\75\105\108\108\105\110\103 "..m.Name;while c.MF and m.Parent and m:FindFirstChild("Humanoid")and m.Humanoid.Health>0 do local ch=v4.Character;local hrp=ch and ch:FindFirstChild("HumanoidRootPart")if mG.o then st="\80\97\117\115\101\100"if hrp then hrp.AssemblyLinearVelocity=v6(0,0,0)end;break end;if mr then mT(mr.Position,0,true)end;pcall(function()mouse1click()keypress(0x32);keyrelease(0x32)end)wait(c.CD)end else st="\83\101\97\114\99\104\105\110\103"end;wait(0.1)else st="\80\97\117\115\101\100"wait(0.2)end;wait(0.05)end end)
local function GS()return st end;mG=L.n('\77\97\116\99\104\97 \77\105\110\101\114',v5(400,420),{GS})local ls={}for _,f in ipairs(rb:GetChildren())do table.insert(ls,f.Name)end;local mt=mG:T('Main')local ms=mG:S(mt,'Controls')mG:C(mt,ms,'Enable Miner',false,function(s)c.A=s end)mG:C(mt,ms,'Enable Mob Farm',false,function(s)c.MF=s end)local di;di=mG:DC(mt,ms,'Targets',{},function(v)c.TR=v end,gRT(),'Location','Island2VolcanicDepths',function(v)local nf=rb:FindFirstChild(v)if nf then c.CRF=nf;local nr=gRT()if di then di.ch1=nr;di.v1={}c.TR={}print("Location updated: "..v)end end end,ls)local mdi;mdi=mG:DC(mt,ms,'Mob Targets',{},function(v)c.TM=v end,gMT(),'Refresh Mobs','Click',function()if mdi then mdi.ch1=gMT()print("Mob list refreshed")end end,{'Click'})local s=mG:T('Settings')local mo=mG:S(s,'Movement')mG:Sl(s,mo,'Speed Cap',c.SC,function(v)c.SC=v end,1,10,1,' studs')mG:Sl(s,mo,'Smoothness',c.MS,function(v)c.MS=v end,0.01,1,0.01,'')mG:Sl(s,mo,'Click Delay',c.CD,function(v)c.CD=v end,0.01,1,0.01,'s')local sa=mG:T('Safety')local ss=mG:S(sa,'Avoidance')mG:Sl(sa,ss,'Mob Safe Radius',c.SR,function(v)c.SR=v end,10,100,5,' studs')mG:Sl(sa,ss,'Player Dist',c.PMD,function(v)c.PMD=v end,5,50,5,' studs')mG:Sl(sa,ss,'Mob Evade Dist',c.MAD,function(v)c.MAD=v end,10,50,5,' studs')mG:Sl(sa,ss,'Evade Force',c.AS,function(v)c.AS=v end,1,10,0.5,'')mG:Sl(sa,ss,'Mob Farm Range',c.MFR,function(v)c.MFR=v end,100,5000,100,' studs')while true do if iskeypressed(0x23)then mG:TM(not mG.o)while iskeypressed(0x23)do wait(0.05)end end;mG:St()wait(0.005)end
